apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow
  labels:
    app: workflow
  namespace: namespace-workflow-1715940306928
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow
  template:
    metadata:
      labels:
        app: workflow
    spec:
      containers:
        - name: workflow
          image: acrworkflow1715940306928.azurecr.io/image-workflow-1715940306928:latest
          ports:
            - containerPort: 8080