apiVersion: v1
kind: Service
metadata:
  name: workflow
  namespace: namespace-workflow-1715940504120
spec:
  type: LoadBalancer
  selector:
    app: workflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080