apiVersion: v1
kind: Service
metadata:
  name: myWorkflow
  namespace: namespace-workflow-1716232948945
spec:
  type: LoadBalancer
  selector:
    app: myWorkflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080