apiVersion: v1
kind: Service
metadata:
  name: milind
  namespace: namespace-workflow-1715940025860
spec:
  type: LoadBalancer
  selector:
    app: milind
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080